---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: mesolite
# description will be included in the image's metadata
description: This is my personal Bluefin-dx image with native Steam and some other bling.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable # latest is also supported if you want new updates ASAP
alt-tags:
    - stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
    - type: os-release
      properties:
          ID: mesolite
          NAME: Mesolite
          PRETTY_NAME: Mesolite Image
          VARIANT_ID: mesolite-dx
          IMAGE_ID: mesolite-dx
          RELEASE_TYPE: stable

    # scrips to run
    - type: script
      scripts:
          - bling.sh
          - fixes.sh

    - type: files
      files:
          - source: system
            destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

    - type: fonts
      fonts:
          nerd-fonts:
              - BigBlueTerminal
              - FiraCode
              - GeistMono
              - VictorMono
              - Mononoki

    # package installation section
    - from-file: modules/gnome-extensions.yml
    - from-file: modules/flatpaks.yml
    - from-file: modules/packages-dnf.yml
    - from-file: modules/systemd.yml

    - type: gschema-overrides
      include:
          - zz1-mesolite-modifications.gschema.override

    - type: signing # this sets up the proper policy & signing files for signed images to work fully
