# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: mesolite
# description will be included in the image's metadata
description: This is my personal Bluefin-dx image with native Steam and some other bling.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # scrips to run
  - type: script
    scripts:
      - bling.sh

  - type: dnf
    repos:
      nonfree: negativo17
    remove:
      auto-remove: true
      packages:
        - gnome-tweaks
    install:
      packages:
        - blender
        - godot
        - input-remapper
        - mangohud
        - steam

  - from-file: flatpaks.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
